### ISSUE TITLE
Recommended configuration for ImpulseResponse

### ISSUE THREAD

**Issue by LearnedVector** [SRPOL-AUI/storir#3]
Great work on this @masztalskipiotr and @zkwiatkowska. What's the recommended configuration for the ImpulseReponse parameters found here https://github.com/SRPOL-AUI/storir/blob/master/example.py#L6-L10. 

When creating a dataset for augmentation, would it best to just choose random parameters when generating the rir?

**Comment by masztalskipiotr** [comment]
Hi @LearnedVector!

The IR parameters will quite heavily depend on your use case. For example, if you want to simulate large rooms with high reverberation times you'll want to assign larger values to these parameters etc. For starters, I would try the same values as used in our paper. 

As far as randomness is concerned, we sample each parameter from a range to make our augmented dataset more diverse.

**Comment by LearnedVector** [comment]
@masztalskipiotr thanks!
